import { z } from "zod";
import { Type, Property } from "@prisma/client";

export const PostDetailsSchema = z.object({
  description: z.string().min(40).max(500),
  utilities: z.string().optional(),
  income: z.string().min(1).optional(),
  pet: z.string().optional(),
  size: z.number().int().min(1).optional(),
  school: z.number().optional(),
  bus: z.number().optional(),
  restaurant: z.number().optional(),
});

export const CreatePostSchema = z.object({
  title: z.string().min(5).max(50),
  price: z.number().int().min(1),
  images: z.array(z.string()).optional(),
  address: z.string(),
  city: z.string(),
  bedroom: z.number().int().min(1),
  bathroom: z.number().int().min(1),
  latitude: z.string(),
  longitude: z.string(),
  type: z.string().toUpperCase().pipe(z.nativeEnum(Type)),
  property: z.string().toUpperCase().pipe(z.nativeEnum(Property)),
  postDetails: PostDetailsSchema.optional(),
});

export type CreatePostDataType = z.infer<typeof CreatePostSchema>;

export const UpdatePostSchema = z.object({
  title: z.string().min(5).max(50).optional(),
  price: z.number().int().min(1).optional(),
  images: z.array(z.string()).optional(),
  address: z.string().optional(),
  city: z.string().optional(),
  bedroom: z.number().int().min(1).optional(),
  bathroom: z.number().int().min(1).optional(),
  latitude: z.string().optional(),
  longitude: z.string().optional(),
  type: z.string().toUpperCase().pipe(z.nativeEnum(Type)).optional(),
  property: z.string().toUpperCase().pipe(z.nativeEnum(Property)).optional(),
});

export type UpdatePostDataType = z.infer<typeof UpdatePostSchema>;

const parseNumber = (value: unknown) => {
  if (typeof value === "string") {
    const parsed = parseInt(value, 10);
    if (isNaN(parsed)) {
      throw new Error("Invalid number");
    }
    return parsed;
  }
  if (typeof value === "number") {
    return value;
  }
  throw new Error("Invalid type");
};

export const GetPostsParamsSchema = z.object({
  city: z.string().optional(),
  property: z.string().toUpperCase().pipe(z.nativeEnum(Property)).optional(),
  type: z.string().toUpperCase().pipe(z.nativeEnum(Type)).optional(),
  bedroom: z.preprocess(parseNumber, z.number().int().min(0)).optional(),
  minPrice: z.preprocess(parseNumber, z.number().int().min(0)).optional(),
  maxPrice: z.preprocess(parseNumber, z.number().int().min(1)).optional(),
});

export type GetPostParamType = z.infer<typeof GetPostsParamsSchema>;

const SavedPostSchema = z.object({
  id: z.string().optional(), // id is typically generated by the database, so it might be optional
  userId: z.string(), // ObjectId is treated as a string
  postId: z.string(), // ObjectId is treated as a string
});

export type SavedPostType = z.infer<typeof SavedPostSchema>;

export const FetchedPostSchema = z.object({
  id: z.string().optional(), // id is typically generated by the database, so it might be optional
  title: z.string(),
  price: z.number(),
  images: z.array(z.string()),
  address: z.string(),
  city: z.string(),
  bedroom: z.number(),
  bathroom: z.number(),
  latitude: z.string(),
  longitude: z.string(),
  type: z.nativeEnum(Type),
  property: z.nativeEnum(Property),
  createdAt: z.date().optional(), // default now() in the database
  userId: z.string(), // assuming ObjectId is stored as a string
  isSaved: z.boolean().optional(),
  postDetails: PostDetailsSchema.optional(),
  savedPosts: z.array(SavedPostSchema).optional(),
});

export type FetchedPostType = z.infer<typeof FetchedPostSchema>;
